-- MySQL Script generated by MySQL Workbench
-- Mon Jan 18 21:35:20 2021
-- Model: VinylCollection    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`VINYLS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`VINYLS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`VINYLS` (
  `ID_VINYLS` INT NOT NULL AUTO_INCREMENT,
  `TITLE` VARCHAR(70) NOT NULL,
  `YEAR` INT NOT NULL,
  `RATING` FLOAT NULL,
  `COMMENT` MEDIUMTEXT NULL,
  PRIMARY KEY (`ID_VINYLS`),
  UNIQUE INDEX `TITLE_UNIQUE` (`TITLE` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ARTISTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ARTISTS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ARTISTS` (
  `ID_ARTISTS` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `ABOUT` MEDIUMTEXT NULL,
  PRIMARY KEY (`ID_ARTISTS`),
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GENRES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`GENRES` ;

CREATE TABLE IF NOT EXISTS `mydb`.`GENRES` (
  `ID_GENRES` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_GENRES`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VINYLS_has_ARTISTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`VINYLS_has_ARTISTS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`VINYLS_has_ARTISTS` (
  `VINYLS_ID_VINYLS` INT NOT NULL,
  `ARTISTS_ID_ARTISTS` INT NOT NULL,
  PRIMARY KEY (`VINYLS_ID_VINYLS`, `ARTISTS_ID_ARTISTS`),
  INDEX `fk_VINYLS_has_ARTISTS_ARTISTS1_idx` (`ARTISTS_ID_ARTISTS` ASC) VISIBLE,
  INDEX `fk_VINYLS_has_ARTISTS_VINYLS_idx` (`VINYLS_ID_VINYLS` ASC) VISIBLE,
  CONSTRAINT `fk_VINYLS_has_ARTISTS_VINYLS`
    FOREIGN KEY (`VINYLS_ID_VINYLS`)
    REFERENCES `mydb`.`VINYLS` (`ID_VINYLS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VINYLS_has_ARTISTS_ARTISTS1`
    FOREIGN KEY (`ARTISTS_ID_ARTISTS`)
    REFERENCES `mydb`.`ARTISTS` (`ID_ARTISTS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VINYLS_has_GENRES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`VINYLS_has_GENRES` ;

CREATE TABLE IF NOT EXISTS `mydb`.`VINYLS_has_GENRES` (
  `VINYLS_ID_VINYLS` INT NOT NULL,
  `GENRES_ID_GENRES` INT NOT NULL,
  PRIMARY KEY (`VINYLS_ID_VINYLS`, `GENRES_ID_GENRES`),
  INDEX `fk_VINYLS_has_GENRES_GENRES1_idx` (`GENRES_ID_GENRES` ASC) VISIBLE,
  INDEX `fk_VINYLS_has_GENRES_VINYLS1_idx` (`VINYLS_ID_VINYLS` ASC) VISIBLE,
  CONSTRAINT `fk_VINYLS_has_GENRES_VINYLS1`
    FOREIGN KEY (`VINYLS_ID_VINYLS`)
    REFERENCES `mydb`.`VINYLS` (`ID_VINYLS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VINYLS_has_GENRES_GENRES1`
    FOREIGN KEY (`GENRES_ID_GENRES`)
    REFERENCES `mydb`.`GENRES` (`ID_GENRES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SONGS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SONGS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SONGS` (
  `ID_SONGS` INT NOT NULL AUTO_INCREMENT,
  `TITLE` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_SONGS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VINYLS_has_SONGS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`VINYLS_has_SONGS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`VINYLS_has_SONGS` (
  `VINYLS_ID_VINYLS` INT NOT NULL,
  `SONGS_ID_SONGS` INT NOT NULL,
  PRIMARY KEY (`VINYLS_ID_VINYLS`, `SONGS_ID_SONGS`),
  INDEX `fk_VINYLS_has_SONGS_SONGS1_idx` (`SONGS_ID_SONGS` ASC) VISIBLE,
  INDEX `fk_VINYLS_has_SONGS_VINYLS1_idx` (`VINYLS_ID_VINYLS` ASC) VISIBLE,
  CONSTRAINT `fk_VINYLS_has_SONGS_VINYLS1`
    FOREIGN KEY (`VINYLS_ID_VINYLS`)
    REFERENCES `mydb`.`VINYLS` (`ID_VINYLS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VINYLS_has_SONGS_SONGS1`
    FOREIGN KEY (`SONGS_ID_SONGS`)
    REFERENCES `mydb`.`SONGS` (`ID_SONGS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
